name: noondaygame
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  http: ^0.13.6
  cloud_firestore: ^5.6.7
  js: ^0.7.1+1


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/backgrounds/
    - assets/images/roles/
    - assets/images/profilePictures/
  fonts:
    - family: Rye
      fonts:
        - asset: assets/fonts/Rye-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web: 
    generate: true
    image_path: "assets/images/backgrounds/app_icon.jpg"
    background_color: "#2C1810"
    theme_color: "#8B4513"
  windows:
    generate: true
    image_path: "assets/images/backgrounds/app_icon.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/backgrounds/app_icon.jpg"
  image_path: "assets/images/backgrounds/app_icon.jpg"
  adaptive_icon_background: "#2C1810"
  adaptive_icon_foreground: "assets/images/backgrounds/app_icon.jpg"
