name: noondaygame
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  http: ^0.13.6
  cloud_firestore: ^5.6.7
  js: ^0.7.1+1


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/backgrounds/western_town_bg.png
    - assets/images/backgrounds/saloon_bg.png
    - assets/images/backgrounds/western_town_night_bg.jpg
    - assets/images/roles/

  fonts:
    - family: Rye
      fonts:
        - asset: assets/fonts/Rye-Regular.ttf
