// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkGgcMkUwsUrrb4QyzCbkZNDAAum1xo2o',
    appId: '1:502833844181:web:8c2eb464a07caaf74b775c',
    messagingSenderId: '502833844181',
    projectId: 'noondaygame',
    authDomain: 'noondaygame.firebaseapp.com',
    storageBucket: 'noondaygame.firebasestorage.app',
    measurementId: 'G-82XGFK6X89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQhwpV4NWNwqbNrg5CS85VPBeV3y2Ce_4',
    appId: '1:502833844181:android:ba8e4bb8c672c9fb4b775c',
    messagingSenderId: '502833844181',
    projectId: 'noondaygame',
    storageBucket: 'noondaygame.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAut2d345PRqKl5SA3oXdUEQ6J-N_qLty0',
    appId: '1:502833844181:ios:859e2530a88b00414b775c',
    messagingSenderId: '502833844181',
    projectId: 'noondaygame',
    storageBucket: 'noondaygame.firebasestorage.app',
    iosBundleId: 'com.example.noondaygame',
  );
}
